name: "Release"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Specify tag to create"
        required: true

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022]
    runs-on: ${{ matrix.os }}
    env:
      SQLX_OFFLINE: true
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions: write-all
    steps:
      - uses: actions/checkout@v5

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          rustflags: ""

      - name: Install deps
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: coinor-cbc coinor-libcbc-dev
          version: 1.0
        if: matrix.os != 'windows-2022'

      - name: Compile
        run: cargo build --release

      - name: Create Release
        id: create-release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: ${{ github.event.inputs.tag }}
          draft: true
          prerelease: false

      - name: Dump folder contents (debug)
        run: tree /f /a
        if: matrix.os == 'windows-2022'

      - name: Tar XZ the binary (Linux)
        run: tar -C target/release -cJf kural-${{ matrix.os }}-x64.tar.xz kural
        if: matrix.os != 'windows-2022'

      - name: Upload asset (Linux)
        run: |
          gh release upload ${{ github.event.inputs.tag }} ./kural-${{ matrix.os }}-x64.tar.xz
        if: matrix.os != 'windows-2022'

      - name: Tar GZ the binary (Windows)
        run: tar -C target/release -czf kural-${{ matrix.os }}-x64.tar.gz kural.exe
        if: matrix.os == 'windows-2022'

      - name: Upload asset (Windows)
        run: |
          gh release upload ${{ github.event.inputs.tag }} ./kural-${{ matrix.os }}-x64.tar.gz
        if: matrix.os == 'windows-2022'
